k9s:
  cluster: kind-ithalab-cluster-2
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - goldpinger
      - default
  view:
    active: pod
  featureGates:
    nodeShell: false
  proxy: null
