k9s:
  cluster: kind-test
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: context
  featureGates:
    nodeShell: false
  proxy: null
