k9s:
  cluster: kind-kind-cluster
  namespace:
    active: monitoring
    lockFavorites: false
    favorites:
      - monitoring
      - all
      - default
  view:
    active: namespace
  featureGates:
    nodeShell: false
  proxy: null
